# Generated by Django 5.1.7 on 2026-08-23 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_billingreminderdelivery'),
        ('common', '0010_disable_public_landing_monitor_by_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlanQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('invoiced', 'Invoiced'), ('payment_review', 'Payment Review'), ('paid', 'Paid'), ('activation_pending', 'Activation Pending'), ('activated', 'Activated'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending_review', max_length=24)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('normalized_customer_email', models.EmailField(db_index=True, max_length=254)),
                ('organization_name', models.CharField(max_length=255)),
                ('normalized_organization_name', models.CharField(db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('initial_email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('requested_limits', models.JSONField(default=dict)),
                ('approved_limits', models.JSONField(blank=True, default=dict)),
                ('quoted_price_bdt', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_network', models.CharField(blank=True, choices=[('bsc', 'BNB Smart Chain'), ('ethereum', 'Ethereum'), ('tron', 'Tron'), ('ton', 'TON')], max_length=16)),
                ('owner_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('activation_intent_digest', models.CharField(blank=True, db_index=True, max_length=64)),
                ('activation_intent_created_at', models.DateTimeField(blank=True, null=True)),
                ('activation_intent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('activation_intent_used_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomPlanSetupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('normalized_email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('quote_submission', 'Custom Quote Submission'), ('plan_activation', 'Custom Plan Activation'), ('checkout', 'Standard Checkout')], db_index=True, default='quote_submission', max_length=32)),
                ('code_digest', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='paymentinvoice',
            name='unique_active_invoice_per_normalized_email',
        ),
        migrations.RemoveConstraint(
            model_name='paymentinvoice',
            name='unique_active_invoice_per_normalized_org',
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='base_usdt_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='confirmations_reached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='confirmations_required',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='exception_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='fx_rate_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='fx_rate_source',
            field=models.CharField(blank=True, default='runtime_billing_config', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_detected', 'Payment detected'), ('confirming', 'Confirming'), ('verifying', 'Verifying'), ('paid', 'Paid'), ('review_required', 'Review required'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('replaced', 'Replaced'), ('manual_review', 'Manual review'), ('payment_rejected', 'Payment rejected'), ('rejected', 'Rejected')], default='pending', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='paymentinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'verifying', 'payment_detected', 'confirming'))), fields=('normalized_customer_email',), name='unique_active_invoice_per_normalized_email'),
        ),
        migrations.AddConstraint(
            model_name='paymentinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'verifying', 'payment_detected', 'confirming'))), fields=('normalized_organization_name',), name='unique_active_invoice_per_normalized_org'),
        ),
        migrations.AddField(
            model_name='customplanquote',
            name='activated_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_quotes', to='common.organization'),
        ),
        migrations.AddField(
            model_name='customplanquote',
            name='activated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_custom_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customplanquote',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_quote', to='billing.paymentinvoice'),
        ),
        migrations.AddField(
            model_name='customplanquote',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_custom_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsecurityauditevent',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='billing.customplanquote'),
        ),
        migrations.AddField(
            model_name='customplansetupsession',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_sessions', to='billing.customplanquote'),
        ),
        migrations.AddField(
            model_name='customplansetupsession',
            name='email_verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.emailverification'),
        ),
    ]
