# Generated by Django 5.1.7 on 2026-08-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_customplanquote_customplansetupsession_and_more'),
        ('common', '0010_disable_public_landing_monitor_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_invoices', to='common.organization'),
        ),
    ]
