# Generated by Django 5.1.7 on 2026-08-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_paymentinvoice_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='features_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='support_workspace_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
