# Generated by Django 5.1.7 on 2026-08-25 21:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_plan_badge_text_plan_button_text_plan_features_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='crypto_amount',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=28),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='crypto_symbol',
            field=models.CharField(default='USDT', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='oracle_usd_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='payment_asset',
            field=models.CharField(choices=[('usdt', 'USDT (Stablecoin)'), ('native', 'Native Token (BNB, TRX, GRAM, ETH)')], default='usdt', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='rate_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='token_contract',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
