# Generated by Django 5.1.7 on 2026-09-05 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_paymentinvoice_crypto_amount_and_more'),
        ('common', '0013_billingconfiguration_usd_price_display_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSumoBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('production', 'Production')], max_length=16)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSumoOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('terms', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSumoSignupChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('digest', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='channel',
            field=models.CharField(choices=[('direct', 'Direct'), ('appsumo', 'AppSumo')], default='direct', max_length=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='access_type',
            field=models.CharField(choices=[('recurring', 'Recurring'), ('lifetime', 'Lifetime')], default='recurring', max_length=16),
        ),
        migrations.CreateModel(
            name='AppSumoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=48)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppSumoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('encrypted_code', models.TextField()),
                ('masked_code', models.CharField(max_length=20)),
                ('revoked', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='billing.appsumobatch')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.organization')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppSumoEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=16)),
                ('activated_at', models.DateTimeField()),
                ('terms_snapshot', models.JSONField(default=dict)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appsumo_entitlement', to='common.organization')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.appsumooffer')),
            ],
        ),
        migrations.AddField(
            model_name='appsumobatch',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.appsumooffer'),
        ),
        migrations.CreateModel(
            name='AppSumoRefundPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('committed_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppSumoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('imports', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AppSumoSendReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('state', models.CharField(default='reserved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='billing.appsumousage')),
            ],
        ),
        migrations.CreateModel(
            name='AppSumoImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('payload_digest', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='appsumo_import_key')],
            },
        ),
        migrations.CreateModel(
            name='AppSumoTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limits', models.JSONField(default=dict)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiers', to='billing.appsumooffer')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
            ],
            options={
                'ordering': ['tier'],
                'constraints': [models.UniqueConstraint(fields=('offer', 'tier'), name='appsumo_offer_tier')],
            },
        ),
        migrations.AddConstraint(
            model_name='appsumousage',
            constraint=models.UniqueConstraint(fields=('organization', 'start'), name='appsumo_usage_window'),
        ),
        migrations.AddConstraint(
            model_name='appsumosendreservation',
            constraint=models.UniqueConstraint(fields=('usage', 'key'), name='appsumo_send_key'),
        ),
    ]
