import { useEffect, useState } from "react";
import api from "../services/api";
import { getUser } from "../utils/auth";

export default function AccountAdmin() {
  const role = getUser().role;
  const [account, setAccount] = useState(null);
  const [users, setUsers] = useState([]);
  const [form, setForm] = useState({ name: "", email: "", username: "", password: "", role: "operator" });
  const [error, setError] = useState("");
  const load = () => Promise.all([api.get("/account/"), role === "admin" ? api.get("/users/") : Promise.resolve({ data: [] })]).then(([a, u]) => { setAccount(a.data); setUsers(u.data.results || u.data); });
  useEffect(() => { load().catch((e) => setError(e.response?.data?.detail || "Unable to load account.")); }, []);
  const createUser = async (event) => { event.preventDefault(); setError(""); try { await api.post("/users/", form); setForm({ name: "", email: "", username: "", password: "", role: "operator" }); await load(); } catch (e) { setError(e.response?.data?.detail || JSON.stringify(e.response?.data || "Unable to create user.")); } };
  if (!account) return <div className="text-slate-400">Loading account...</div>;
  const cards = [["Users", account.user_count, account.max_users], ["SMTP accounts", account.smtp_count, account.max_smtp_accounts], ["Recipients", account.recipient_count, account.max_recipients], ["Daily emails", account.usage.daily_sent, account.daily_email_limit], ["Monthly emails", account.usage.monthly_sent, account.monthly_email_limit], ["Campaigns today", account.usage.campaigns_today, account.max_campaigns_per_day]];
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">{account.name}</h1><p className="text-sm text-slate-400">Account status: <span className={account.status === "active" ? "text-emerald-400" : "text-rose-400"}>{account.status}</span></p></div>{error && <div className="p-3 bg-rose-500/10 border border-rose-500/30 text-rose-300 rounded-xl text-sm">{error}</div>}<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{cards.map(([label, used, limit]) => <div key={label} className="p-5 bg-slate-900 border border-slate-800 rounded-2xl"><p className="text-xs uppercase text-slate-400">{label}</p><p className="text-2xl font-bold mt-2">{used} <span className="text-sm text-slate-500">/ {limit}</span></p><p className="text-xs text-indigo-400 mt-1">{Math.max(limit - used, 0)} remaining</p></div>)}</div>{role === "admin" && <><form onSubmit={createUser} className="p-5 bg-slate-900 border border-slate-800 rounded-2xl grid md:grid-cols-5 gap-3"><h2 className="md:col-span-5 font-semibold">Add account user</h2>{["name", "email", "username", "password"].map((key) => <input key={key} required type={key === "password" ? "password" : key === "email" ? "email" : "text"} placeholder={key} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />)}<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="manager">Manager</option><option value="operator">Operator</option><option value="viewer">Viewer</option></select><button className="bg-indigo-600 rounded-xl py-2">Create user</button></form><div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-x-auto"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td>{user.name || user.username}</td><td>{user.email}</td><td>{user.role}</td><td>{user.is_active ? "Active" : "Disabled"}</td></tr>)}</tbody></table></div></>}</div>;
}
