# Generated by Django 5.1.7 on 2026-08-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_disable_public_landing_monitor_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfiguration',
            name='addon_admin_price',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='billingconfiguration',
            name='addon_email_10k_price',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='billingconfiguration',
            name='addon_recipient_10k_price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='billingconfiguration',
            name='addon_smtp_price',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='billingconfiguration',
            name='addon_user_price',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
