# Generated by Django 5.1.7 on 2026-08-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_billingconfiguration_addon_admin_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfiguration',
            name='custom_plan_max_self_serve_price_bdt',
            field=models.PositiveIntegerField(default=15000),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='default_reply_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='default_sender_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='default_sender_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='media_storage_path',
            field=models.CharField(default='/app/media/', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='unsubscribe_footer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
