# Generated by Django 5.1.7 on 2026-08-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_disable_public_landing_monitor_by_default'),
        ('users', '0003_user_two_factor_backup_codes_user_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='common.organization'),
        ),
    ]
